Better login handling...
Simply require user@host on the command line and ask for password at the
login command. As soon as the session is expired, the login command has
to be used again.

No state is stored anywhere, so login sessions are gone when exiting.
(the sid may be valid anyway for some time when logout is not used)

~/src/git/pmCommand.py/src (develop) 10-$ ./pmCommand.py -v
admin@10.140.11.30
DEBUG: Using pmCommand version UNRELEASED
(Cmd) listipdus
ERROR: Please login first.
(Cmd) login
Password:
DEBUG: Logging into url https://10.140.11.30/appliance/avtrans as admin
DEBUG: Login successful, got sid: 1571b6280f9ba35518c8e80960ff5906
DEBUG: Session idle timeout: 86400
(Cmd) status
  Outlet      Name          Status      Current (A)
  ==========  ============  ==========  ===========
  power2[1]   hpswitch      OFF         0.0
  power2[2]   klaasje       ON          0.0
  power2[3]   20-ba-aeP0_1  ON          0.0
  power2[4]   20-ba-aeP0_1  ON(locked)  0.0
  power2[5]   20-ba-aeP0_1  OFF         0.0
  power2[6]   20-ba-aeP0_1  OFF         0.0
  power2[7]   20-ba-aeP0_1  OFF         0.0
  power2[8]   20-ba-aeP0_1  ON          0.0
  power2[9]   20-ba-aeP0_1  ON          0.0
  power2[10]  20-ba-aeP0_1  ON          0.0
  [...]
(Cmd) logout
INFO: Logout successful.
(Cmd) listipdus
ERROR: Invalid session, please login first.